language: rust
sudo: false
os: linux
dist: trusty

rust:
  - stable

branches:
  except:
    - staging.tmp
    - trying.tmp

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never

env:
  global:
    - RUST_BACKTRACE=full

script:
  - cargo build --verbose --all
  - cargo doc   --verbose --all --no-deps

  - cargo test  --verbose --all
  - cargo test  --verbose --all --features serde

  #  unic-ucd-normal is used in unic-ucd with non-default feature
  - cargo test  --verbose --manifest-path unic/ucd/normal/Cargo.toml

  # == Nightly-only ==

  - test "$TRAVIS_RUST_VERSION" != "nightly" ||
    cargo test  --verbose --all --all-features

  # This takes too long, let's disable for now.
  - test "$TRAVIS_RUST_VERSION" != "nightly" ||
    cargo build --benches --verbose --all --features 'bench_it'

# TODO: - rustdoc --test README.md -L target/debug -L target/debug/deps

# TODO: Enable auto update for gh-pages
#after_success: |
#  cargo doc && \
#  echo '<meta http-equiv="refresh" content="0;url=YOURLIBNAME/index.html">' > target/doc/index.html && \
#  sudo pip install ghp-import && \
#  ghp-import -n target/doc && \
#  git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
