[package]
name = "unic-ucd-normal"
version = "0.7.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC — Unicode Character Database — Normalization Properties"
keywords = ["text", "unicode", "normalization"]
categories = ["internationalization", "text-processing", "parsing", "rendering"]

# No tests/benches that depends on /data/
exclude = ["tests/conformance_tests.rs"]

[dependencies]
unic-char-property = { path = "../../char/property/", version = "0.7.0" }
unic-char-range = { path = "../../char/range", version = "0.7.0" }
unic-ucd-category = { path = "../category/", version = "0.7.0", optional = true }
unic-ucd-hangul = { path = "../hangul/", version = "0.7.0" }
unic-ucd-version = { path = "../version/", version = "0.7.0" }

[dev-dependencies]
unic-ucd-category = { path = "../category/", version = "0.7.0" }

[features]
default = []
unstable = []

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "behnam/rust-unic" }
is-it-maintained-open-issues = { repository = "behnam/rust-unic" }
appveyor = { repository = "behnam/rust-unic", branch = "master", service = "github" }
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
