[package]
name = "unic-ucd-name"
version = "0.7.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC — Unicode Character Database — Name"
keywords = ["text", "unicode", "character-property", "name"]
categories = ["internationalization", "text-processing", "parsing", "rendering"]

# No tests/benches that depends on /data/
exclude = []

[dependencies]
unic-ucd-version = { path = "../version/", version = "0.7.0" }
unic-ucd-hangul = { path = "../hangul/", version = "0.7.0" }
unic-char-property = { path = "../../char/property/", version = "0.7.0" }


[features]
default = []
unstable = [
    "unic-ucd-version/unstable",
    "unic-ucd-hangul/unstable",
    "unic-char-property/unstable",
]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "behnam/rust-unic" }
is-it-maintained-open-issues = { repository = "behnam/rust-unic" }
appveyor = { repository = "behnam/rust-unic", branch = "master", service = "github" }
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
