[package]
name = "unic-idna"
version = "0.7.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC — Unicode IDNA Compatibility Processing"
keywords = ["text", "unicode", "idna", "internationalized", "domain-names"]
categories = ["internationalization", "text-processing", "parsing", "rendering"]
readme = "README.md"

# No tests/benches that depends on /data/
exclude = ["tests/conformance_tests.rs"]

[dependencies]
matches = "0.1"
unic-idna-punycode = { path = "punycode/", version = "0.7.0" }
unic-idna-mapping = { path = "mapping/", version = "0.7.0" }
unic-normal = { path = "../normal/", version = "0.7.0" }
unic-ucd-bidi = { path = "../ucd/bidi/", version = "0.7.0" }
unic-ucd-normal = { path = "../ucd/normal/", version = "0.7.0" }
unic-ucd-version = { path = "../ucd/version/", version = "0.7.0" }

[features]
default = []
unstable = [
    "unic-idna-punycode/unstable",
    "unic-idna-mapping/unstable",
    "unic-normal/unstable",
    "unic-ucd-bidi/unstable",
    "unic-ucd-normal/unstable",
    "unic-ucd-version/unstable",
]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "behnam/rust-unic" }
is-it-maintained-open-issues = { repository = "behnam/rust-unic" }
appveyor = { repository = "behnam/rust-unic", branch = "master", service = "github" }
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
